# Generated by Django 4.2.7 on 2025-10-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(choices=[('plush', 'Плюшевые игрушки'), ('constructor', 'Конструкторы'), ('doll', 'Куклы'), ('educational', 'Развивающие игрушки'), ('creative', 'Творческие наборы')], max_length=20, verbose_name='Категория')),
                ('image', models.ImageField(blank=True, upload_to='products/', verbose_name='Изображение')),
                ('year', models.IntegerField(verbose_name='Год производства')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
