# Generated by Django 4.2.7 on 2025-10-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.CharField(default='Россия', max_length=100, verbose_name='Страна производства'),
        ),
    ]
