# Generated by Django 4.2.7 on 2025-11-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_category_product_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, default='', verbose_name='Причина отказа'),
        ),
    ]
